//! Configuration for protobuf compilation.

use std::path::PathBuf;

use crate::path_map::PathMap;

/// Configuration for compiling protobuf files.
///
/// This struct contains all the settings needed to compile protobuf files
/// and generate Rust code with additional helper functions.
#[derive(Debug, Clone)]
pub struct CompileConfig {
    /// Path to the file descriptor set binary file.
    ///
    /// This file contains the compiled protobuf descriptors and is
    /// typically generated by `protoc --descriptor_set_out`.
    pub file_descriptor_set_path: PathBuf,

    /// Output directory for generated Rust files.
    ///
    /// All generated Rust code will be written to this directory.
    pub output_path: PathBuf,

    /// Whether to format the generated code.
    ///
    /// When set to `true`, the generated Rust code will be formatted
    /// using rustfmt before being written to files.
    pub format: bool,

    /// API-specific configuration options.
    ///
    /// Controls generation of API-related helper functions and utilities.
    pub api: ApiConfig,

    /// External path mappings for custom type handling.
    ///
    /// Maps protobuf type paths to custom Rust types for integration
    /// with external libraries or custom implementations.
    pub external_paths: PathMap,
}

/// Configuration for API-specific code generation.
///
/// Controls the generation of various helper functions and utilities
/// that are commonly needed when working with protobuf APIs.
#[derive(Debug, Clone)]
pub struct ApiConfig {
    /// Generate name helper functions.
    ///
    /// When set to `true`, generates functions for getting the name
    /// of messages and enums, useful for debugging and logging.
    pub names: bool,

    /// Generate field name helper functions.
    ///
    /// When set to `true`, generates functions for getting the names
    /// of fields within messages, useful for reflection and debugging.
    pub field_names: bool,

    /// Generate type URL helper functions.
    ///
    /// When set to `true`, generates functions for getting the type URL
    /// of messages, useful for Google APIs and Any type handling.
    pub type_url: bool,

    /// Generate oneof utility functions.
    ///
    /// When set to `true`, generates utility functions for working with
    /// oneof fields, including getters and setters.
    pub oneof_utility: bool,

    /// Optional domain prefix for generated types.
    ///
    /// When specified, adds the given domain prefix to generated type names,
    /// useful for avoiding name conflicts in multi-domain APIs.
    pub domain: Option<String>,

    /// Generate serde serialization support.
    ///
    /// When set to `true`, generates Serialize and Deserialize implementations
    /// for all protobuf messages and enums.
    pub serde: bool,

    /// Optional name for the helpers module.
    ///
    /// When specified, creates a module with the given name containing
    /// all generated helper functions. If `None`, helpers are placed
    /// in the same module as the message.
    pub helpers_mod: Option<String>,
}

impl Default for CompileConfig {
    fn default() -> Self {
        Self {
            file_descriptor_set_path: PathBuf::from(std::env::var_os("OUT_DIR").unwrap())
                .join("fd.pb"),
            output_path: std::env::var_os("OUT_DIR").unwrap().into(),
            format: true,
            api: ApiConfig::default(),
            external_paths: PathMap::default(),
        }
    }
}

impl Default for ApiConfig {
    fn default() -> Self {
        Self {
            names: true,
            field_names: true,
            type_url: true,
            oneof_utility: true,
            domain: None,
            serde: true,
            helpers_mod: None,
        }
    }
}
